
spring:
  datasource:
      driverClassname: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/cloud_note?serverTimezone=GMT%2B8"
      username: root
      password: root
  liquibase:
    enabled: true
    change-log: classpath:/db/change-log.xml

mybatis:
  config-location: classpath:mybatis/MybatisConfig.xml
  type-aliases-package: pers.sjh.cloud_note.domain
  mapper-locations: classpath:mybatis/mapper/*.xml


