
spring:
  datasource:
      driverClassname: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_main?useSSL=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: root
  liquibase:
    enabled: true
    change-log: classpath:/db/change-log.xml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  config-location: classpath:mapper/mybatis_config.xml
  type-aliases-package: pers.sjh.springboot.domain
  mapper-locations: classpath:mapper/*/*.xml


